/**
 * Centralized WebSocket Events Configuration
 * Primary Source: Module 3 (Section 25) & Module 6 (Section 33, 34)
 */

export const SOCKET_EVENTS = {
  // Connection lifecycle
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CONNECT_ERROR: 'connect_error',
  RECONNECT: 'reconnect',
  RECONNECT_ATTEMPT: 'reconnect_attempt',

  // Room Subscription
  JOIN_ROOM: 'join',
  LEAVE_ROOM: 'leave',
  SUBSCRIBE_HOSPITAL: 'subscribe_hospital',
  UNSUBSCRIBE_HOSPITAL: 'unsubscribe_hospital',
  SUBSCRIBE_EMERGENCY: 'subscribe_emergency',
  UNSUBSCRIBE_EMERGENCY: 'unsubscribe_emergency',

  // Incoming Emergency Alerts
  EMERGENCY_CREATED: 'EMERGENCY_CREATED',
  NEW_INCOMING_EMERGENCY: 'NEW_INCOMING_EMERGENCY',
  AMBULANCE_ASSIGNED: 'AMBULANCE_ASSIGNED',

  // Live Location & Dynamic ETA Stream
  AMBULANCE_LOCATION_UPDATED: 'AMBULANCE_LOCATION_UPDATED',
  LOCATION_UPDATED: 'LOCATION_UPDATED', // Canonical alias
  ETA_UPDATED: 'ETA_UPDATED',
  ROUTE_UPDATED: 'ROUTE_UPDATED',

  // Emergency & Ambulance Status Changes
  STATUS_UPDATED: 'STATUS_UPDATED',
  PATIENT_ONBOARD: 'PATIENT_ONBOARD',
  AMBULANCE_ARRIVED: 'AMBULANCE_ARRIVED',
  HOSPITAL_ARRIVED: 'HOSPITAL_ARRIVED',
  EMERGENCY_COMPLETED: 'EMERGENCY_COMPLETED',
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',

  // Cascading Fallback Dispatch Events
  FALLBACK_STARTED: 'FALLBACK_STARTED',
  FALLBACK_TRIGGERED: 'FALLBACK_TRIGGERED',
  AMBULANCE_REASSIGNED: 'AMBULANCE_REASSIGNED',
  FALLBACK_ASSIGNMENT_CREATED: 'FALLBACK_ASSIGNMENT_CREATED',
  FALLBACK_ASSIGNMENT_UPDATED: 'FALLBACK_ASSIGNMENT_UPDATED',

  // Hospital Resource Sync
  HOSPITAL_RESOURCES_UPDATED: 'HOSPITAL_RESOURCES_UPDATED',
  RESOURCES_UPDATED: 'RESOURCES_UPDATED',
};
