/**
 * Emergency Request & Ambulance Lifecycle Statuses
 * Primary Source: Module 3 & Module 6 Technical Specifications
 */

export const EMERGENCY_STATUS = {
  ASSIGNED: 'ASSIGNED',
  DRIVER_ACCEPTED: 'DRIVER_ACCEPTED',
  ACCEPTED: 'ACCEPTED',
  EN_ROUTE_TO_PATIENT: 'EN_ROUTE_TO_PATIENT',
  ARRIVED_AT_PATIENT: 'ARRIVED_AT_PATIENT',
  PATIENT_ONBOARD: 'PATIENT_ONBOARD',
  EN_ROUTE_TO_HOSPITAL: 'EN_ROUTE_TO_HOSPITAL',
  ARRIVED_AT_HOSPITAL: 'ARRIVED_AT_HOSPITAL',
  ARRIVED: 'ARRIVED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  TIMEOUT: 'TIMEOUT',
  FALLBACK: 'FALLBACK',
  NO_AMBULANCE_AVAILABLE: 'NO_AMBULANCE_AVAILABLE',
};

export const EMERGENCY_TYPES = {
  CARDIAC: 'CARDIAC',
  ACCIDENT: 'ACCIDENT',
  TRAUMA: 'TRAUMA',
  RESPIRATORY: 'RESPIRATORY',
  STROKE: 'STROKE',
  GENERAL_MEDICAL: 'GENERAL_MEDICAL',
  OTHER: 'OTHER',
};

/**
 * Status Metadata for presentation, badges, and progress tracking
 */
export const STATUS_CONFIG = {
  [EMERGENCY_STATUS.ASSIGNED]: {
    label: 'Assigned',
    description: 'Ambulance assigned, awaiting driver confirmation',
    severity: 'info',
    color: '#3b82f6',
    bgColor: 'rgba(59, 130, 246, 0.12)',
    borderColor: 'rgba(59, 130, 246, 0.35)',
    step: 1,
  },
  [EMERGENCY_STATUS.DRIVER_ACCEPTED]: {
    label: 'Driver Accepted',
    description: 'Driver confirmed dispatch and response',
    severity: 'info',
    color: '#2563eb',
    bgColor: 'rgba(37, 99, 235, 0.12)',
    borderColor: 'rgba(37, 99, 235, 0.35)',
    step: 2,
  },
  [EMERGENCY_STATUS.ACCEPTED]: {
    label: 'Accepted',
    description: 'Driver confirmed dispatch',
    severity: 'info',
    color: '#2563eb',
    bgColor: 'rgba(37, 99, 235, 0.12)',
    borderColor: 'rgba(37, 99, 235, 0.35)',
    step: 2,
  },
  [EMERGENCY_STATUS.EN_ROUTE_TO_PATIENT]: {
    label: 'En Route to Patient',
    description: 'Ambulance moving toward incident location',
    severity: 'critical',
    color: '#dc2626',
    bgColor: 'rgba(220, 38, 38, 0.12)',
    borderColor: 'rgba(220, 38, 38, 0.35)',
    step: 3,
  },
  [EMERGENCY_STATUS.ARRIVED_AT_PATIENT]: {
    label: 'Arrived at Patient',
    description: 'Paramedics on scene providing initial stabilization',
    severity: 'success',
    color: '#16a34a',
    bgColor: 'rgba(22, 163, 74, 0.12)',
    borderColor: 'rgba(22, 163, 74, 0.35)',
    step: 4,
  },
  [EMERGENCY_STATUS.PATIENT_ONBOARD]: {
    label: 'Patient Onboard',
    description: 'Patient secured in ambulance, preparing for hospital transit',
    severity: 'info',
    color: '#3b82f6',
    bgColor: 'rgba(59, 130, 246, 0.14)',
    borderColor: 'rgba(59, 130, 246, 0.45)',
    step: 5,
  },
  [EMERGENCY_STATUS.EN_ROUTE_TO_HOSPITAL]: {
    label: 'En Route to Hospital',
    description: 'Ambulance in transit to hospital emergency bay',
    severity: 'critical',
    color: '#dc2626',
    bgColor: 'rgba(220, 38, 38, 0.14)',
    borderColor: 'rgba(220, 38, 38, 0.45)',
    step: 6,
  },
  [EMERGENCY_STATUS.ARRIVED_AT_HOSPITAL]: {
    label: 'Arrived at Hospital',
    description: 'Ambulance has reached hospital emergency entrance',
    severity: 'success',
    color: '#16a34a',
    bgColor: 'rgba(22, 163, 74, 0.14)',
    borderColor: 'rgba(22, 163, 74, 0.45)',
    step: 7,
  },
  [EMERGENCY_STATUS.ARRIVED]: {
    label: 'Arrived',
    description: 'Ambulance has reached facility',
    severity: 'success',
    color: '#16a34a',
    bgColor: 'rgba(22, 163, 74, 0.14)',
    borderColor: 'rgba(22, 163, 74, 0.45)',
    step: 7,
  },
  [EMERGENCY_STATUS.COMPLETED]: {
    label: 'Completed',
    description: 'Patient transferred, incident closed',
    severity: 'success',
    color: '#16a34a',
    bgColor: 'rgba(22, 163, 74, 0.12)',
    borderColor: 'rgba(22, 163, 74, 0.35)',
    step: 8,
  },
  [EMERGENCY_STATUS.REJECTED]: {
    label: 'Driver Rejected',
    description: 'Driver declined, initiating cascading fallback',
    severity: 'warning',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.35)',
    step: 0,
  },
  [EMERGENCY_STATUS.TIMEOUT]: {
    label: 'Driver Timeout',
    description: 'Driver response timer expired, initiating cascading fallback',
    severity: 'warning',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.35)',
    step: 0,
  },
  [EMERGENCY_STATUS.FALLBACK]: {
    label: 'Cascading Fallback',
    description: 'Re-running dispatch algorithm for alternative ambulance',
    severity: 'warning',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.35)',
    step: 0,
  },
  [EMERGENCY_STATUS.NO_AMBULANCE_AVAILABLE]: {
    label: 'No Ambulance Available',
    description: 'Candidate pool exhausted, escalating to dispatch control',
    severity: 'critical',
    color: '#dc2626',
    bgColor: 'rgba(220, 38, 38, 0.14)',
    borderColor: 'rgba(220, 38, 38, 0.45)',
    step: 0,
  },
};

export const EMERGENCY_TYPE_CONFIG = {
  [EMERGENCY_TYPES.CARDIAC]: {
    label: 'Cardiac Emergency',
    color: '#ef4444',
    bgColor: 'rgba(239, 68, 68, 0.14)',
    borderColor: 'rgba(239, 68, 68, 0.35)',
    priority: 'CRITICAL',
    requiredResources: ['ICU Bed', 'Ventilator', 'Defibrillator'],
  },
  [EMERGENCY_TYPES.ACCIDENT]: {
    label: 'Traffic Collision / Accident',
    color: '#f97316',
    bgColor: 'rgba(249, 115, 22, 0.14)',
    borderColor: 'rgba(249, 115, 22, 0.35)',
    priority: 'HIGH',
    requiredResources: ['Trauma Bay', 'General Bed', 'Blood Bank'],
  },
  [EMERGENCY_TYPES.TRAUMA]: {
    label: 'Severe Trauma',
    color: '#f43f5e',
    bgColor: 'rgba(244, 63, 94, 0.14)',
    borderColor: 'rgba(244, 63, 94, 0.35)',
    priority: 'CRITICAL',
    requiredResources: ['Operating Room', 'ICU Bed', 'Blood Supply'],
  },
  [EMERGENCY_TYPES.RESPIRATORY]: {
    label: 'Respiratory Distress',
    color: '#06b6d4',
    bgColor: 'rgba(6, 182, 212, 0.14)',
    borderColor: 'rgba(6, 182, 212, 0.35)',
    priority: 'HIGH',
    requiredResources: ['Ventilator', 'ICU Bed', 'Oxygen Delivery'],
  },
  [EMERGENCY_TYPES.STROKE]: {
    label: 'Acute Stroke / Neuro',
    color: '#a855f7',
    bgColor: 'rgba(168, 85, 247, 0.14)',
    borderColor: 'rgba(168, 85, 247, 0.35)',
    priority: 'CRITICAL',
    requiredResources: ['CT Scan', 'ICU Bed', 'Neurology Team'],
  },
  [EMERGENCY_TYPES.GENERAL_MEDICAL]: {
    label: 'General Medical Emergency',
    color: '#3b82f6',
    bgColor: 'rgba(59, 130, 246, 0.14)',
    borderColor: 'rgba(59, 130, 246, 0.35)',
    priority: 'MEDIUM',
    requiredResources: ['Emergency Bay', 'General Bed'],
  },
  [EMERGENCY_TYPES.OTHER]: {
    label: 'Unspecified Emergency',
    color: '#94a3b8',
    bgColor: 'rgba(148, 163, 184, 0.14)',
    borderColor: 'rgba(148, 163, 184, 0.35)',
    priority: 'MEDIUM',
    requiredResources: ['Triage Bay', 'General Bed'],
  },
};

export const LIFECYCLE_STEPS = [
  { id: 'ASSIGNED', label: 'Assigned', shortDesc: 'Dispatched' },
  { id: 'DRIVER_ACCEPTED', label: 'Accepted', shortDesc: 'Confirmed' },
  { id: 'EN_ROUTE_TO_PATIENT', label: 'En Route to Patient', shortDesc: 'Transit' },
  { id: 'ARRIVED_AT_PATIENT', label: 'On Scene', shortDesc: 'Stabilizing' },
  { id: 'PATIENT_ONBOARD', label: 'Patient Onboard', shortDesc: 'Loaded' },
  { id: 'EN_ROUTE_TO_HOSPITAL', label: 'En Route to Hospital', shortDesc: 'Incoming' },
  { id: 'ARRIVED_AT_HOSPITAL', label: 'Arrived at Hospital', shortDesc: 'At Bay' },
  { id: 'COMPLETED', label: 'Completed', shortDesc: 'Transferred' },
];
